services:
    ubuntu:
        public: true
        container_name: hai945
        image: imlala/ubuntu-xfce-vnc-novnc:latest
        ports:
            - 8618:8618
        environment: 
            - VNC_PASSWD=leon3441
            - GEOMETRY=1280x768
            - TZ=Asia/Shanghai
            - DEPTH=24
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 1000m
          memory: 3072Mi
          storage:
            size: 5Gi
            class: standard
